// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmvosbaclhavgifrfelw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptdm9zYmFjbGhhdmdpZnJmZWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDYyMzksImV4cCI6MjA3MDQ4MjIzOX0.OO4caRaqx-JXTSNGBl9V5iduGmLtb6hhTmIr4yhLCSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});